/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
    "./node_modules/konsta/**/*.{js,vue,ts}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': 'var(--k-color-primary, #ffa800)',
        'md-light-primary': 'var(--k-color-md-light-primary, #ffa800)',
        'md-dark-primary': 'var(--k-color-md-dark-primary, #ffb951)',
        'md-light-on-primary': 'var(--k-color-md-light-on-primary, #ffffff)',
        'md-dark-on-primary': 'var(--k-color-md-dark-on-primary, #452b00)',
        'md-light-primary-container': 'var(--k-color-md-light-primary-container, #ffdf9e)',
        'md-dark-primary-container': 'var(--k-color-md-dark-primary-container, #633f00)',
        'md-light-on-primary-container': 'var(--k-color-md-light-on-primary-container, #2b1700)',
        'md-dark-on-primary-container': 'var(--k-color-md-dark-on-primary-container, #ffddb3)',
        'md-light-surface': 'var(--k-color-md-light-surface, #fbf8f2)',
        'md-dark-surface': 'var(--k-color-md-dark-surface, #0e233d)',
        'md-light-on-surface': 'var(--k-color-md-light-on-surface, #1d1b16)',
        'md-dark-on-surface': 'var(--k-color-md-dark-on-surface, #e6e1d9)',
        'md-light-surface-variant': 'var(--k-color-md-light-surface-variant, #ebe1d4)',
        'md-dark-surface-variant': 'var(--k-color-md-dark-surface-variant, #1d3b61)',
        'md-light-on-surface-variant': 'var(--k-color-md-light-on-surface-variant, #4d4639)',
        'md-dark-on-surface-variant': 'var(--k-color-md-dark-on-surface-variant, #90a4bc)',
        'md-light-surface-1': 'var(--k-color-md-light-surface-1, #f6f3ed)',
        'md-dark-surface-1:': 'var(--k-color-md-dark-surface-1, #132b49)',
        'md-dark-surface-1': 'var(--k-color-md-dark-surface-1, #132b49)',
        'md-light-surface-2': 'var(--k-color-md-light-surface-2, #f0ede7)',
        'md-dark-surface-2': 'var(--k-color-md-dark-surface-2, #1a3556)',
        'md-light-surface-3': 'var(--k-color-md-light-surface-3, #eae7e1)',
        'md-dark-surface-3': 'var(--k-color-md-dark-surface-3, #213f64)',
        'md-light-surface-4': 'var(--k-color-md-light-surface-4, #e5e1db)',
        'md-dark-surface-4': 'var(--k-color-md-dark-surface-4, #24436a)',
        'md-light-surface-5': 'var(--k-color-md-light-surface-5, #dfdbd4)',
        'md-dark-surface-5': 'var(--k-color-md-dark-surface-5, #2b4b75)',
        'md-light-outline': 'var(--k-color-md-light-outline, #7f7667)',
        'md-dark-outline': 'var(--k-color-md-dark-outline, #8c9db0)',
        'md-light-outline-variant': 'var(--k-color-md-light-outline-variant, #d1c5b4)',
        'md-dark-outline-variant': 'var(--k-color-md-dark-outline-variant, #1d3b61)',
        'md-light-secondary': 'var(--k-color-md-light-secondary, #488be3)',
        'md-dark-secondary': 'var(--k-color-md-dark-secondary, #93c5fd)',
        'md-light-on-secondary': 'var(--k-color-md-light-on-secondary, #ffffff)',
        'md-dark-on-secondary': 'var(--k-color-md-dark-on-secondary, #0c2340)',
        'md-light-secondary-container': 'var(--k-color-md-light-secondary-container, #dbeafe)',
        'md-dark-secondary-container': 'var(--k-color-md-dark-secondary-container, #1e3e5e)',
        'md-dark-on-secondary-container': 'var(--k-color-md-dark-on-secondary-container, #bfdbfe)',
        'md-light-on-secondary-container': 'var(--k-color-md-light-on-secondary-container, #1e3a8a)',
        'ios-primary': 'var(--k-color-ios-primary, #ffa800)',
        'ios-primary-tint': 'var(--k-color-ios-primary-tint, #ffb833)',
        'ios-primary-shade': 'var(--k-color-ios-primary-shade, #e69700)',
        'ios-light-surface': '#efeff4',
        'ios-light-surface-1': '#fff',
        'ios-light-surface-2': '#f7f7f8',
        'ios-light-surface-3': '#fff',
        'ios-dark-surface': '#000',
        'ios-dark-surface-1': '#1c1c1d',
        'ios-dark-surface-2': '#121212',
        'ios-dark-surface-3': '#1c1c1d',
        'ios-light-surface-variant': '#f4f4f4',
        'ios-dark-surface-variant': '#232323',
        'st-navy': {
          DEFAULT: '#0c2340',
          50: '#f0f4f9',
          100: '#dce5f1',
          200: '#bccfe5',
          300: '#91b3d4',
          400: '#5e91be',
          500: '#3c73a7',
          600: '#2c5b8b',
          700: '#234970',
          800: '#1e3e5e',
          900: '#0c2340',
          950: '#071527',
        },
        'st-blue': {
          DEFAULT: '#488BE3',
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#488BE3',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        'st-yellow': {
          DEFAULT: '#ffa800',
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#ffa800',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        'st-sidewalk': {
          DEFAULT: '#f5f3ee',
          50: '#fdfdfc',
          100: '#fbfaf8',
          200: '#f5f3ee',
          300: '#eae6db',
          400: '#ded7c4',
          500: '#cec2a8',
          600: '#b9a98b',
          700: '#9b8b6f',
          800: '#7f725b',
          900: '#685e4b',
        },
        'dark-bg': '#071527',
        'dark-card': '#0e233d',
        'dark-border': '#1d3b61',
        'dark-muted': '#90a4bc',
        'light-bg': '#f5f3ee',
        'light-card': '#ffffff',
        'light-border': '#ded7c4',
        'light-text': '#0c2340',
      },
      fontFamily: {
        serif: ['"DM Serif Display"', 'Georgia', 'serif'],
        sans: ['"Inter"', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        article: ['"Lora"', 'Georgia', 'serif'],
      },
    },
  },
  plugins: [],
}
